### ISSUE TITLE
html5 doen't start

### ISSUE THREAD

**Issue by Metreas** [alangecker/bigbluebutton-docker#100]
Hello,

I have now tried to install the container several times. Unfortunately, however, there is always an error on the HTML5 client.

`html5_1       | nice: setpriority(-2): Permission denied
html5_1       | 2021/02/15 14:29:44 Command exited with error: exit status 1`

`bbb-docker_html5_1 exited with code 1`

The error leads to a 502 error when opening the conference (https://bbb.****.de/html5client/join?sessionToken=qb7nrtqt7udlzept). The other components, such as greenlight, seem to be running.

**Comment by alangecker** [comment]
that is wired. there should be no place where `nice` is set in the html5 container in the `v2.2.x` - but there is a related change upcoming in `v2.3.x`.

On which branch are you? did you maybe switch the branch back to `v2.2.x` without recreating the images?
in this (or a similar) case, maybe following helps:
`$ ./scripts/compose build`

**Comment by Metreas** [comment]
Yes, I work on the branch `v2.2.x` without changing the version.

But your solution with the rebuild worked. Thank you very much.
