### ISSUE TITLE
Error starting userland proxy: listen tcp4 10.7.7.1:5000: bind: address already in use

### ISSUE THREAD

**Issue by ghost** [alangecker/bigbluebutton-docker#105]
```
ERROR: for greenlight  Cannot start service greenlight: driver failed programming external connectivity on endpoint bbb-docker_greenlight_1 (ecd89202fbc145d76926d20dafc388c2bd4b21f15cf3b4d3dddc471edd0c19cc): Error starting userland proxy: listen tcp4 10.7.7.1:5000: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

I already have port 5000 used by my docker registry service. How can I change the port to something else and make sure bbb still works? I know there is a docker-compose.greenlight.yml file that has port 5000. But if I change this file, will there be additional configs that need to be updated as well?

**Comment by alangecker** [comment]
additionally the greenlight port is used in the nginx config, which you should change as well ;)
https://github.com/alangecker/bigbluebutton-docker/blob/v2.2.x/mod/nginx/bbb/greenlight.nginx

**Comment by ghost** [comment]
I've updated both the docker-compose.greenlight.yml and the mod/nginx/bbb/greenlight.nginx to use port 5500. I use `./scripts/compose down` and `./scripts/compose up -d` to restart everything. 

But I am still seeing this:
![image](https://user-images.githubusercontent.com/77554817/109722895-56a85b80-7b7b-11eb-98cb-aa1bdb9e871b.png)



Is there a way (e.g. log) I can diagnose what happened?

Thank you for your kind help.

**Comment by alangecker** [comment]
after changing files of the nginx container, you have to rebuild it with `./scripts/compose build nginx` and an `./scripts/compose up -d` afterwards ;)

**Comment by ghost** [comment]
I have my instance resolved and running. Thank you!
