### ISSUE TITLE
Small customization

### ISSUE THREAD

**Issue by mhingston** [alangecker/bigbluebutton-docker#113]
Thanks for the docker image.

I'd like to make a few small configuration changes such as hiding the public chat when a meeting starts as described [here](https://github.com/bigbluebutton/bigbluebutton/issues/8689#issuecomment-635608171).

I'm not sure how to go about this, do I need to rebuild the bbb-docker_html5 image?

**Comment by cjhille** [comment]
There should be a setting `CHAT_START_CLOSED` for that in `.env`. I believe it was added here https://github.com/alangecker/bigbluebutton-docker/commit/8292fbae607e02aab4aec4844bc9214c1553dddc

**Comment by mhingston** [comment]
Thank you, works perfectly
