### ISSUE TITLE
image Build issue

### ISSUE THREAD

**Issue by nyok92** [alangecker/bigbluebutton-docker#12]
When running for the first time the docker-compose command to build containers :
Step 11/37 : RUN LC_CTYPE=C.UTF-8 add-apt-repository ppa:bigbluebutton/support
 ---> Running in e112ad5ea21b
 This PPA contains package builds that are not part of BigBlueButton itself, but
which are required to use all BigBlueButton features. This includes software not
packaged in Ubuntu and backports of newer packages.

Packages provided in this PPA are compiled with options suitable for use with
BigBlueButton, but might be missing features that other applications require.
 More info: https://launchpad.net/~bigbluebutton/+archive/ubuntu/support
gpg: keyring `/tmp/tmpn_4hd93d/secring.gpg' created
gpg: keyring `/tmp/tmpn_4hd93d/pubring.gpg' created
gpg: requesting key E95B94BC from hkp server keyserver.ubuntu.com
Error: retrieving gpg key timed out.
gpgkeys: key 36A9CA9512E5F0A4BE549ACF2E1B01D0E95B94BC can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
ERROR: Service 'core' failed to build: The command '/bin/sh -c LC_CTYPE=C.UTF-8 add-apt-repository ppa:bigbluebutton/support' returned a non-zero code: 1

**Comment by nyok92** [comment]
But when running the second time, it seems ok:
Building core
Step 1/37 : FROM ubuntu:16.04
 ---> 005d2078bdfa
Step 2/37 : MAINTAINER ffdixon@bigbluebutton.org
 ---> Using cache
 ---> b3ce0ca61e7e
Step 3/37 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> ce29e9d11805
Step 4/37 : ENV container docker
 ---> Using cache
 ---> b7cb0e65228c
Step 5/37 : ENV DOCKERIZE_VERSION v0.6.1
 ---> Using cache
 ---> 7ead93faa4a0
Step 6/37 : RUN apt-get update && apt-get install -y software-properties-common language-pack-en wget apt-utils
 ---> Using cache
 ---> 3cc19f4975dc
Step 7/37 : RUN update-locale LANG=en_US.UTF-8
 ---> Using cache
 ---> 4c03098d29c7
Step 8/37 : RUN LC_CTYPE=C.UTF-8 add-apt-repository ppa:rmescandon/yq
 ---> Using cache
 ---> 65f5d681d3ec
Step 9/37 : RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz     && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz     && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
 ---> Using cache
 ---> 9447d88dbba2
Step 10/37 : RUN apt-get install -y supervisor apt-transport-https equivs libreoffice haveged ttf-liberation net-tools
 ---> Using cache
 ---> 0e9d817d959c
Step 11/37 : RUN LC_CTYPE=C.UTF-8 add-apt-repository ppa:bigbluebutton/support
 ---> Running in f958f01c79d9
 This PPA contains package builds that are not part of BigBlueButton itself, but
which are required to use all BigBlueButton features. This includes software not
packaged in Ubuntu and backports of newer packages.

Packages provided in this PPA are compiled with options suitable for use with
BigBlueButton, but might be missing features that other applications require.
 More info: https://launchpad.net/~bigbluebutton/+archive/ubuntu/support
gpg: keyring `/tmp/tmp3ymfyiwy/secring.gpg' created
gpg: keyring `/tmp/tmp3ymfyiwy/pubring.gpg' created
gpg: requesting key E95B94BC from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp3ymfyiwy/trustdb.gpg: trustdb created
gpg: key E95B94BC: public key "Launchpad PPA for BigBlueButton" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Removing intermediate container f958f01c79d9

**Comment by alangecker** [comment]
> ```
> gpg: requesting key E95B94BC from hkp server keyserver.ubuntu.com
> Error: retrieving gpg key timed out.
> ```

apparently your server coudn't connect to `keyserver.ubuntu.com`.  most likely this is unrelated to BBB so I will close this issue ;)
