### ISSUE TITLE
docker running but greenlight showing "Invalid BigBlueButton Endpoint and Secret"

### ISSUE THREAD

**Issue by Amal-David** [alangecker/bigbluebutton-docker#18]
I modified the shared secret in the env file, is there anything else that I would need to modify in order to get this up and running?

Adding some more information to the documentation about the parameters that needs to be modified would be hugely helpful

**Comment by Amal-David** [comment]
It was a DNS mapping issue, it's resolved. I'm amazed how seamless it is! Thanks for the work @alangecker

**Comment by PeerConradi** [comment]
Hey could you tell me what you did to resolve this?
