### ISSUE TITLE
Suggestion : its better to have hostname than ip address

### ISSUE THREAD

**Issue by Akshay-Hegde** [alangecker/bigbluebutton-docker#19]
https://github.com/alangecker/bigbluebutton-docker/blob/e247cd1a455926e25ad93edad66f6f22eaf03424/scripts/setup#L54

There can be situations like multiple IP address A record, server will have in public dns ( ex : ISP load balancing, ISP backup in case of primary failure ), so I think hardcoding public IP isn't good in my opinion.

**Comment by alangecker** [comment]
you are possibly right, but currently I can't see any reasonable way how you could avoid setting a static IP for freeswitch and kurento.
Can you think of any?
