### ISSUE TITLE
"Require moderator approval" leads to 404 for guests

### ISSUE THREAD

**Issue by cjhille** [alangecker/bigbluebutton-docker#20]
When setting up a room that requires approval for guests to join, the guest is prompted with a 404-page, while the moderator sees the pending request. The moderator is able to approve the request, however the client's "guest-wait.html" page still can't be found.

![image](https://user-images.githubusercontent.com/8192226/86028022-b15c4700-ba31-11ea-86eb-af79097eb6e3.png)

I'm running the current 2.2.x branch (commit e247cd1) with a fresh build, but I've also encountered this issue with previous builds.

The nginx log states:

```
2020/06/29 15:48:02 [error] 7#7: *1231 open() "/etc/nginx/html/client/conf/config.xml" failed (2: No such file or directory), client: 172.31.0.2, server: _, request: "GET /client/conf/config.xml HTTP/1.1", host: "konferenz.REDACTED.de"
2020/06/29 15:48:02 [error] 7#7: *1234 open() "/etc/nginx/html/client/guest-wait.html" failed (2: No such file or directory), client: 172.31.0.2, server: _, request: "GET /client/guest-wait.html?sessionToken=lpxjuoyxnub4kk9l HTTP/1.1", host: "konferenz.REDACTED.de", referrer: "https://konferenz.REDACTED.de/b/adm-x94-oiw"
```

**Comment by alangecker** [comment]
thanks for reporting these issues!

I've just created a PR (#23) which should fix both of them. maybe you can verify that it works for you?

- at first you need to add a line with `ENABLE_WEBHOOKS=true` to `.env`
- then run following commands:
  ```sh
  git fetch
  git checkout develop # switch to develop branch
  ./scripts/upgrade # rebuild images
  ./scripts/compose up -d # restart changed containers
  ```

**Comment by cjhille** [comment]
Wonderful! PR #23 fixes both issues and things work flawlessly now <3
