### ISSUE TITLE
how can we help for the recording ?

### ISSUE THREAD

**Issue by npettiaux** [alangecker/bigbluebutton-docker#4]
how can we help for the recording ?

**Comment by alangecker** [comment]
I did not had a deeper look into it, but steps would probably be:

- enable recording (`disableRecordingDefault=false`) in `/mod/core/web/bigbluebutton.properties`
- ensure that all recorded files are on shared docker volumes. (already the case for `/var/bigbluebutton`) On the official setup they are in following paths:
  ```
  raw_audio_src: /var/freeswitch/meetings
  raw_video_src: /usr/share/red5/webapps/video/streams
  kurento_video_src: /var/kurento/recordings
  kurento_screenshare_src: /var/kurento/screenshare
  raw_screenshare_src: /usr/share/red5/webapps/screenshare/streams
  raw_webrtc_deskshare_src: /usr/share/red5/webapps/video-broadcast/streams
  raw_deskshare_src: /var/bigbluebutton/deskshare
  raw_presentation_src: /var/bigbluebutton
  ```
- develop a container with access to these volumes which processes the recordings. Most files for that should be in [bbb-record-core](https://github.com/alangecker/bbb-packages/tree/master/bbb-record-core) and `bbb-playback-*`
- ensure that nginx serves the files propably

**Comment by alangecker** [comment]
there is finally recording with the [Release v2.2.23-1](https://github.com/alangecker/bigbluebutton-docker/pull/55) :tada:
