### ISSUE TITLE
which container does the command bbb-conf reside in?

### ISSUE THREAD

**Issue by liuwen** [alangecker/bigbluebutton-docker#41]
thanks for the owner, I got BBB 2.2.x up and running fine. Though I checked every container but I couldn't find the command `bbb-conf`, which is required for obtaining secrets for API developing and such. So how can I run this command?

**Comment by alangecker** [comment]
`bbb-conf` is heavily depended on the ubuntu 16.04 setup and won't work at all with the docker containers.

there are other ways to do the same, but currently not well documented yet.
- the `SHARED_SECRET` for API access is stored in `.env`
- logs, (re-)starting,.. you can achieve with `./scripts/compose` (see docker-compose manual for exact commands)

**Comment by liuwen** [comment]
> `bbb-conf` is heavily depended on the ubuntu 16.04 setup and won't work at all with the docker containers.
> 
> there are other ways to do the same, but currently not well documented yet.
> 
> * the `SHARED_SECRET` for API access is stored in `.env`
> * logs, (re-)starting,.. you can achieve with `./scripts/compose` (see docker-compose manual for exact commands)

Thanks man, "SHARED_SECRET" in `.env` works for me. 

Before I asked I tried to look for outputs during installation in literally every container with various search case-insensitive strings like 'secret', 'bbb-conf' , but no luck.

**Comment by alangecker** [comment]
> Thanks man, "SHARED_SECRET" in `.env` works for me.

cool, that I could help! :)
