### ISSUE TITLE
Setup script doesnt parse IPv4/v6 correctly

### ISSUE THREAD

**Issue by trickert76** [alangecker/bigbluebutton-docker#48]
I found out, that the IP 192.168.0.1 is not accepted by the regex. On the otherhand 300.300.300.300 is accepted. The same with the IPv6 regex, because it makes the v4 regex. I'm not able to enter a IPv6 address manually in the setup.

**Comment by alangecker** [comment]
ah thanks for reporing this issue!

I've just pushed a fix, it should work now: https://github.com/alangecker/bigbluebutton-docker/commit/2b28bac2fe7d969b41ea66c13cce2f23e4687075

it still matches a lot of invalid IP adresses like `300.300.300.300` or `2000a5::::f`, so its only a rough validation, but at least all valid IP adresses should now be accepted.


exact validation is, escpecially for IPv6, quite unreadable... :D

- IPv4: `^([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$`
- IPv6 `^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$`

_source: https://helloacm.com/how-to-valid-ipv6-addresses-using-bash-and-regex/_
