### ISSUE TITLE
Unable to get recordings to work

### ISSUE THREAD

**Issue by kdoubledubs** [alangecker/bigbluebutton-docker#56]
I am successfully able to click the record button and i am seeing the counter count up during the recording.  After ending the meeting I do not see any recordings.

After looking at the container logs I have noted that bbb-docker_recordings_1 container is not even running.  It is getting this error. 

Error starting command: `/entrypoint.sh` - fork/exec /entrypoint.sh: permission denied

I am not sure what to do.

**Comment by kdoubledubs** [comment]
Made the entrypoint.sh file in the mod/recordings executable.

the file was not set properly.

```
chmod +x entrypoint.sh
```

**Comment by alangecker** [comment]
yeps, somehow the permission got lost again.
I've just pushed a fix to the main branch:
https://github.com/alangecker/bigbluebutton-docker/commit/a4e93eacd041f3ac05c8c811fa1cb61daf46155f=

for others with the issue: an `./scripts/upgrade` should solve this now :)
