### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by weeman1337** [alangecker/bigbluebutton-docker#61]
Hey @alangecker ,

during this year's Hacktoberfest we gathered a handful of people who want to help improving the BBB container setup.

If you could provide us more issues here about work you think that should be done that would help.

Best regards  
Michael

**Comment by alangecker** [comment]
hey @weeman1337 
nice to hear, that you want to work on this project! :)

currently I see following smaller or bigger open tasks:

### more stability
A vision of this project is, that **checking out a specific commit leads to the exact same version of BBB**.

The official ubuntu/debian repository doesn't provide any older versions. In the `core` part we still use packages directly from these repos which leads regullary to following situation:

There was an BBB update released, immediately building the bbb-docker core image uses these new packages, but some changes to configuration files in the `bbb-docker` project are required but still missing -> `bbb-docker` is in a broken state for days until the repo gets updated.

##### The resulting task to tackle this problem would be:
* Remove the ubuntu repository dependency from `core` by either
  1. using the officially built packages, but from tracking git repo specifically built for this purpose https://github.com/alangecker/bbb-packages
  2. building the components directly from the [bigbluebutton/bigbluebutton](https://github.com/bigbluebutton/bigbluebutton) source (which would be amazing but difficult!)
* While rewriting anyway, this can be combined with #26, which was already done a little bit within https://github.com/alangecker/bigbluebutton-docker/pull/31/commits/541297ba15f4c106bc2f6923ea0361f446a68b50 @ `v2.3.x`

### better usability
there where discussions regarding the way docker-compose is used. #42  #47 
recently I tried to create a proposal how a new 'tooling' could look alike: https://github.com/alangecker/bigbluebutton-docker/issues/42#issuecomment-687874343
maybe there is someone how can think that further or even implement it? :)

### better 'debugability'
almost every problem with BBB leads to the same error in Greenlight: [#35 Invalid BigBlueButton Endpoint and Secret](https://github.com/alangecker/bigbluebutton-docker/issues/35)

this is not very helpful, so I thought utilizing docker healthchecks (#37) could help people with troubleshooting issues.

## generally...
... if you need anything, I'm always happy to answer questions :)

**Comment by alangecker** [comment]
now that october has passed, I assume that I probably can close the issue? :D
