### ISSUE TITLE
Invalid interpolation format for "enviroment" option in service "core"

### ISSUE THREAD

**Issue by JonaZz747** [alangecker/bigbluebutton-docker#73]
Hi,

I tried installing from stock on an Ubuntu 18.04 host.
I went through the Steps in the [README-file](https://github.com/alangecker/bigbluebutton-docker/blob/ad502a25876a984ddf64385ec87231200522343c/README.md). In step `4. Start containers` I got the above mentioned error:
`ERROR: Invalid interpolation format for "enviroment" option in service "core": "DEV_MODE:-}"`

**Comment by viaregio** [comment]
I had this error too. The solution was to update docker-compose with `pip install -U docker-compose`. The version installed by apt seems to old.

**Comment by alangecker** [comment]
@JonaZz747
does the hint about upgrading `docker-compose` solve the issue for you? :)

I would also like to add a note in the `README` for the minimum docker-compose version. maybe you could tell us which version you use right now?

```
$ docker-compose --version
docker-compose version 1.27.4, build 1110ad01
```

**Comment by viaregio** [comment]
If you install `docker-compose` on Ubuntu 18.04 with apt you get version 1.17.1-2 (at the time of writing this).

**Comment by JonaZz747** [comment]
> If you install `docker-compose` on Ubuntu 18.04 with apt you get version 1.17.1-2 (at the time of writing this).

I can confirm that:
```
$ docker-compose --version
docker-compose version 1.17.1, build unknown
```

> The solution was to update docker-compose with `pip install -U docker-compose`.

Still not working for me. I had to use `pip3` because 
```
$ pip install -U docker-compose
Collecting docker-compose
...(shortened)...
Downloading https://files.pythonhosted.org/packages/7d/ae/90ddcf28fb8eee5d4990920586d2856342e42faa95f39223f0b9762ef264/pyrsistent-0.17.2.tar.gz (106kB)
    100% |████████████████████████████████| 112kB 6.9MB/s 
pyrsistent requires Python '>=3.5' but the running Python is 2.7.17
```
`pip3` finishes installing `docker-compose` but when executing
```
$ docker-compose --version
docker-compose version 1.17.1, build unknown
```
it's still the old version.
Removing the docker-compose that was installed by `apt` and removing the one installed by `pip3` and then reinstalling the one by `pip3` doesn't solve this issue:
```
$ docker-compose
bash: /usr/bin/docker-compose: No such file or directory
```

**Comment by alangecker** [comment]
the official installation instructions suggest to use following commands to install `docker-compose`:

```bash
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```
https://docs.docker.com/compose/install/

maybe this works for you?

**Comment by JonaZz747** [comment]
Yep, that did the trick. Thanks!

May I suggest that @alangecker adds something in the docu for solving this problem on older os (like mine)?

---

BTW: I've now got docker-compose version 1.27.4 installed:
```
$ /usr/local/bin/docker-compose --version
docker-compose version 1.27.4, build 40524192
```
