### ISSUE TITLE
no option for recording sessions

### ISSUE THREAD

**Issue by mghadam** [alangecker/bigbluebutton-docker#77]
I can't find any options in the conference room / admin area to record sessions, is this option available in bigbluebutton-docker ?

**Comment by alangecker** [comment]
there is the `ENABLE_RECORDING` option in the `.env` file.
https://github.com/alangecker/bigbluebutton-docker/blob/7e60db384e5c0a7d8d66c3a7d5144246d752a526/sample.env#L27-L33

setting it to `true` should do the job! :)
in this example the `#` means, that it is only a comment. you would set it to `true` by removing the hash.

**Comment by mghadam** [comment]
Thank you so much, it worked. I see you have added the instructions in sample.env file to make it clear.
