### ISSUE TITLE
Fails runing webrtc-sfu Dockerfile

### ISSUE THREAD

**Issue by lupa18** [alangecker/bigbluebutton-docker#8]
cp: cannot stat 'config/default.example.yml': No such file or directory

where can I find such file?

thanks in advance !

**Comment by alangecker** [comment]
the file should be in `./bbb-webrtc-sfu/config/`. Maybe the `bbb-webrtc-sfu` folder is still empty, because, you cloned the repo without `--recurse-submodules`?

you can still checkout the submodule belated with `git submodule update --init`

**Comment by lupa18** [comment]
yes ! that solve it ! thanks!!
