### ISSUE TITLE
env option to support german freeswitch audio files

### ISSUE THREAD

**Issue by cjhille** [alangecker/bigbluebutton-docker#83]
This is a feature request for the (optional) inclusion of the German Freeswitch audio files, which someone just localized. I haven't heard all of them, but they sound about right :) 
Issue thread: https://github.com/bigbluebutton/bigbluebutton/issues/1843#issuecomment-747454392
Repo: https://github.com/Daedalus3/freeswitch-german-soundfiles

**Comment by alangecker** [comment]
will be included in the release [v.2.2.31-2](https://github.com/alangecker/bigbluebutton-docker/pull/85)! :) 

german language can be archived by following setting in `.env`
`SOUNDS_LANGUAGE=de-de-daedalus3`

note, that the german "you are now (un-)muted" announcement is really long, so maybe rather deactivate it with
`DISABLE_SOUND_MUTED=true`

**Comment by cjhille** [comment]
Thank you! And you're probably right about the "(un-)muted" audio. There also seems to be a bit of an initial delay (~.5s) with the 'conf-unmuted.wav' file. Maybe @Daedalus3 can provide a shorter version such as:
* "Mikrofon eingeschaltet" instead of "Ihr Mikrofon ist nun wieder aktiv"
* "Mikrofon stummgeschaltet" instead of "Ihr Mikrofon ist jetzt auf stumm"

**Comment by Daedalus3** [comment]
Thanks for the feedback -I shortened both files.
