### ISSUE TITLE
 ubuntu 18.04 Errors

### ISSUE THREAD

**Issue by Aevermann** [alangecker/bigbluebutton-docker#95]
on ubuntu 18.04
Docker version 19.03.6, build 369ce74a3c
docker-compose version 1.17.1
I get a lot of those:
```
ERROR: Invalid interpolation format for "environment" option in service "core": "${DEV_MODE:-}"
ERROR: Invalid interpolation format for "environment" option in service "core": "${WELCOME_MESSAGE:-}"
ERROR: Invalid interpolation format for "environment" option in service "html5": "${DEV_MODE:-}"
ERROR: Invalid interpolation format for "environment" option in service "freeswitch": "${SIP_IP_ALLOWLIST:-}"
ERROR: Invalid interpolation format for "environment" option in service "kurento": "${NETWORK_INTERFACE:-}"

```
so how to fix this?

**Comment by alangecker** [comment]
docker-compose 1.17.1 was released `2017-11-08`, there were already some other issues due to outdated docker-compose versions.
Maybe trying it with a more recent version could help?
You can find instructions how to install it here: https://docs.docker.com/compose/install/

**Comment by Aevermann** [comment]
wow that fixed it. thx, didnt realize ubuntu publishes such an outdated version of docker-compose. thank you very  much for your help.
