### ISSUE TITLE
Firewall odity

### ISSUE THREAD

**Issue by Aevermann** [alangecker/bigbluebutton-docker#96]
Hi (again). If i disable the ufw  firewall bbb video is fine, everything
works.
But if I enable one ufw (with the required ports opened) the video stream
doesn't go through (error 1020).

UFW Settings:
To                         Action      From
--                         ------      ----
22/tcp                     ALLOW IN    Anywhere
80/tcp                     ALLOW IN    Anywhere
443/tcp                    ALLOW IN    Anywhere
7443/tcp                   ALLOW IN    Anywhere
8443/tcp                   ALLOW IN    Anywhere
16384:32768/udp            ALLOW IN    Anywhere
3478/tcp                   ALLOW IN    Anywhere
22/tcp (v6)                ALLOW IN    Anywhere (v6)
80/tcp (v6)                ALLOW IN    Anywhere (v6)
443/tcp (v6)               ALLOW IN    Anywhere (v6)
7443/tcp (v6)              ALLOW IN    Anywhere (v6)
8443/tcp (v6)              ALLOW IN    Anywhere (v6)
16384:32768/udp (v6)       ALLOW IN    Anywhere (v6)
3478/tcp (v6)              ALLOW IN    Anywhere (v6)

with netcat I can connect to all required ports with or without ufw enabled
What do I miss here?

I wanted to look @

 /opt/freeswitch/etc/freeswitch/autoload_configs/switch.conf.xml 
to ensure ethe ports matching 
    <param name="rtp-start-port" value="16384"/>
    <param name="rtp-end-port" value="32784"/>

but  docker  exec -it bbb-docker_freeswitch_1 bash ..ed into and cant find the file?  

Thx for your support &  thx for your great work btw.

**Comment by alangecker** [comment]
Keep in mind that there is also quite some networking happening between containers, which might be also get blocked :)

haven't tried it, but  maybe something like this could help?
```
ufw allow in on docker0
ufw allow out on docker0
```

**Comment by Aevermann** [comment]
thx that worked perfectly. Sry for late reply.
