### ISSUE TITLE
Localhost

### ISSUE THREAD

**Issue by hacko2** [alangecker/bigbluebutton-docker#97]
hi, i cant  run in localhost machine. Fail to obtain certificates for coturn and freeswitch.

**Comment by alangecker** [comment]
for running it localhost, you have do use the "dev mode": https://github.com/alangecker/bigbluebutton-docker/blob/v2.2.x/docs/development.md

but even with dev mode, coturn won't work due to the still missing certificates

**Comment by hacko2** [comment]
I already have a stun/turn external server yet I am getting an error to connect ESL and to get certificates, i'm tired and I don't know how to make this work.

**Comment by hacko2** [comment]
webrtc-sfu_1   | 2021-02-08T10:56:06.949Z - error: [mcs-balancer] Failed to connect to media server url=ws://kurento:8888/kurento, ip=127.0.0.1, mediaType=undefined, retries=3
core_1         | bbb-fsesl-akka | 2021-02-08T10:56:08.249Z ERROR o.b.f.v.f.ConnectionManager - Failed to connect to ESL

i tried with localhost ip and external ip and still cant.

**Comment by alangecker** [comment]
somehow the containers can't reach each other, do you have any firewall running?
maybe try:
- `sudo systemctl stop firewalld && sudo systemctl restart docker`
- `sudo ufw disable`

**Comment by hacko2** [comment]
It only lets me if I put my private IP, ok I'll tell you everything and see if you can help me:

I have a KVM with UBUNTU 16.04 8gb of ram and a turn / stun server on the same network, a DNS configured for my public ip.
My dns always crashes with letsencrypt, I can buy my own certificate if you think it's necessary.

When letsencrypt fails, the process creates a self-signed certificate and causes it to block green light, saying that it cannot connect to BBB.

**Comment by hacko2** [comment]
Greenlight fail with connect to BBB shared secret
